### ISSUE TITLE
Information if parameter requires value or not. 

### ISSUE THREAD

**Issue by mzorec** [Azure/azure-docs-cli-python#1056]
We are implementing a build tool and we would like to generate Azure cli tasks from yaml. We are having difficulty figuring out if specific parameter requires value or not.

For example: 

```
- uid: az_login
  name: az login

  parameters:
  - name: --allow-no-subscriptions
    summary: Support access tenants without subscriptions. It's uncommon but useful to run tenant level commands, such as 'az ad'.
    description: ''
  - name: --password -p
    summary: Credentials like user password, or for a service principal, provide client secret or a pem file with key and public certificate. Will prompt if not given.
    description: '' 
```
We can not tell if parameter --password requires a value or not (which type it is). Is it possible to figure this information from current documentation? If not are there any chances that this information will be added in future?
